### ISSUE TITLE
打开页面时有一个资源404

### ISSUE THREAD

**Issue by EmptyDreams** [HCLonely/hexo-bilibili-bangumi#128]
**错误描述**

打开页面时尝试获取`../bangumi/null`资源导致`404`错误。

[错误页面地址](https://kmar.top/bangumis/)

**报错信息（建议使用截图，请尽量截取全部把错误信息）**

![QQ截图20220407234737](https://user-images.githubusercontent.com/44894906/162242731-30712222-d209-4894-a13f-3f984aae057a.jpg)

**插件版本：**1.7.4

**配置信息**

```yml
bangumi:
  enable: true
  source: bili
  path:
  vmid: 66951474
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  lazyload: false
  loading:
  metaColor:
  color:
  webp:
  progress:
cinema: # 追剧设置
  enable: false
  path:
  vmid:
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  loading:
  metaColor:
  color:
  webp:
  progress:
```

**软件信息（使用`hexo -v`命令查看）**

```
hexo: 6.0.0
hexo-cli: 4.3.0
os: win32 10.0.19043
node: 16.14.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1m+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
