### ISSUE TITLE
手动添加的番剧如何调整顺序？

### ISSUE THREAD

**Issue by EmptyDreams** [HCLonely/hexo-bilibili-bangumi#129]
**问题描述**

手动添加番剧之后它总会出现在最后面，有没有办法调整它和自动获取到的番剧的顺序？

**插件版本** 1.7.4

**软件信息（使用`hexo -v`命令查看）**

```yml
hexo: 6.1.0
hexo-cli: 4.3.0
os: win32 10.0.19043
node: 16.14.0
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1m+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
