### ISSUE TITLE
[Bug]: 与 Pjax 的冲突 & bangumi 数据源问题

### ISSUE THREAD

**Issue by Misakamoe** [HCLonely/hexo-bilibili-bangumi#311]
### 问题描述及如何重现此问题

Theme: [butterfly 4.9.0](https://github.com/jerryc127/hexo-theme-butterfly) ---> [Pjax 0.2.8](https://github.com/MoOx/pjax)
Pjax 为主题自带，配置在主题 `_config.yml` 中。

**分以下两种情况：**

- Pjax 打开但未排除 Bangumi 页面

  ```yml
  pjax:
  enable: true
  exclude:
    # - /bangumi/
  ```

  只有第一次点击进入页面正常，后续进入页面出现点击按钮无反应**且**所有番剧都排在一页内，具体表现如下：

  ![pjax-on1](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/104571689/e63a0b3b-4313-4e72-a4c8-bcc3d6634e89)

- Pjax 打开且排除 Bangumi 页面

  ```yml
  pjax:
  enable: true
  exclude:
    - /bangumi/
  ```

  点击进入正常，返回进入异常，且所有番剧都排在一页内，具体表现如下：

  ![pjax-on2](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/104571689/ed12de54-31ea-4b90-bf56-eda4b5601a70)

**hexo-bilibili-bangumi** 的设置如下：

```yml
bangumi:
  enable: true
  source: bgm
  bgmInfoSource: "bgmApi"
  path: bangumi/index.html
  vmid: XXXXXX
  title: "追番"
  quote:
  show: 1
  lazyload: false
  srcValue: "__image__"
  lazyloadAttrName: "data-src=__image__"
  loading:
  showMyComment:
  pagination:
  metaColor: "#58b2dc"
  color:
  webp:
  progress:
  extraOrder:
  proxy:
    host:
    port:
  extra_options:
    key: value
```

---

数据源为 `bangumi` 而非 `bgm` 时，番剧信息获取不完全，以及跳转链接仍为 `bilibili.com`，具体表现如下：

![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/104571689/0afe423c-5348-4aeb-b038-0828bef2a9e1)

**hexo-bilibili-bangumi** 的设置如下：

```yml
bangumi:
  enable: true
  source: bangumi
  bgmInfoSource: "bgmApi"
```

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

![image](https://github.com/HCLonely/hexo-bilibili-bangumi/assets/104571689/bed7ccd7-090d-4bbd-9f16-3dfd430763e8)

### 插件版本

v1.8.7

### 环境信息（使用`hexo -v`命令查看）

```shell
hexo: 6.3.0
hexo-cli: 4.3.1
os: win32 10.0.22621
node: 18.16.0
acorn: 8.8.2
ada: 1.0.4
ares: 1.19.0
brotli: 1.0.9
cldr: 42.0
icu: 72.1
llhttp: 6.0.10
modules: 108
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.2
tz: 2022g
undici: 5.21.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.15
v8: 10.2.154.26-node.26
zlib: 1.2.13
```
