### ISSUE TITLE
用netlify在线部署的时候出现错误

### ISSUE THREAD

**Issue by cfx2020** [HCLonely/hexo-bilibili-bangumi#365]
### 问题描述及如何重现此问题

使用netlify在线部署出现端口错误，用bilibili没问题，用bangumi就报这个错。
```
bangumi: # 追番设置
  enable: true
  source: bgm
  bgmInfoSource: 'bgmApi'
  path: bangumis/index.html
  vmid: 635522
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  lazyload: true
  loading: /img/loading.gif
  metaColor: #808080
  color: #000000
  webp: true
  progress: true
  proxy:
    host: '代理host'
    port: '代理端口'
  extra_options:
    key: value
    lazyload:
      enable: false # 关闭主题自带的懒加载(只关闭番剧页，不影响其他页面)
```

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

```
4:36:04 PM: build.command from netlify.toml                               
4:36:04 PM: ────────────────────────────────────────────────────────────────
4:36:04 PM: ​
4:36:04 PM: $ npm run build
4:36:04 PM: > hexo-site@0.0.0 build /opt/build/repo
4:36:04 PM: > hexo clean && hexo bangumi -u && hexo generate
4:36:04 PM: INFO  Validating config
4:36:05 PM: INFO  Validating config
4:36:06 PM: INFO  Getting bangumis, please wait...
4:36:06 PM: (node:3819) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 代理端口.
4:36:06 PM:     at new NodeError (internal/errors.js:322:7)
4:36:06 PM:     at validatePort (internal/validators.js:216:11)
4:36:06 PM:     at lookupAndConnect (net.js:1013:5)
4:36:06 PM:     at Socket.connect (net.js:989:5)
4:36:06 PM:     at Agent.connect [as createConnection] (net.js:201:17)
4:36:06 PM:     at Agent.createSocket (_http_agent.js:323:26)
4:36:06 PM:     at Agent.addRequest (_http_agent.js:274:10)
4:36:06 PM:     at new ClientRequest (_http_client.js:305:16)
4:36:06 PM:     at TunnelingAgent.request (http.js:94:10)
4:36:06 PM:     at TunnelingAgent.createSocket (/opt/build/repo/node_modules/tunnel/lib/tunnel.js:126:25)
4:36:06 PM:     at TunnelingAgent.createSecureSocket [as createSocket] (/opt/build/repo/node_modules/tunnel/lib/tunnel.js:207:41)
4:36:06 PM:     at TunnelingAgent.addRequest (/opt/build/repo/node_modules/tunnel/lib/tunnel.js:84:8)
4:36:06 PM:     at new ClientRequest (_http_client.js:305:16)
4:36:06 PM:     at Object.request (https.js:370:10)
4:36:06 PM:     at RedirectableRequest._performRequest (/opt/build/repo/node_modules/follow-redirects/index.js:296:24)
4:36:06 PM:     at new RedirectableRequest (/opt/build/repo/node_modules/follow-redirects/index.js:69:8)
4:36:06 PM: (Use `node --trace-warnings ...` to show where the warning was created)
4:36:06 PM: (node:3819) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
4:36:06 PM: (node:3819) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 插件版本

1.8.9

### 环境信息（使用`hexo -v`命令查看）

```shell
4:49:50 PM: hexo: 7.0.0-rc2
4:49:50 PM: hexo-cli: 4.3.1
4:49:50 PM: os: linux 5.10.186-179.751.amzn2.x86_64 Ubuntu 20.04.6 LTS (Focal Fossa)
4:49:50 PM: node: 14.21.3
4:49:50 PM: v8: 8.4.371.23-node.88
4:49:50 PM: uv: 1.42.0
4:49:50 PM: zlib: 1.2.11
4:49:50 PM: brotli: 1.0.9
4:49:50 PM: ares: 1.18.1
4:49:50 PM: modules: 83
4:49:50 PM: nghttp2: 1.42.0
4:49:50 PM: napi: 8
4:49:50 PM: llhttp: 2.1.6
4:49:50 PM: openssl: 1.1.1t
4:49:50 PM: cldr: 40.0
4:49:50 PM: icu: 70.1
4:49:50 PM: tz: 2022f
4:49:50 PM: unicode: 14.0
```
