### ISSUE TITLE
[Bug]: 更新追番数据时出现未预料的输出,且source文件夹中无相关index文件

### ISSUE THREAD

**Issue by lalalll-lalalll** [HCLonely/hexo-bilibili-bangumi#417]
### 问题描述及如何重现此问题

相关配置如下,更新数据失败,为安装插件后的第一次执行

另:请问proxy和extra_options必须填值么?
```
bangumi: # 追番设置
  enable: true
  source: bangumi
  bgmInfoSource: 'bgmApi'
  path: anime/index.html
  vmid: 802016
  title: '追番列表'
  quote: ''
  show: 2
  lazyload: true
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  showMyComment: false
  pagination: false
  metaColor:
  color:
  webp: true
  progress: false
  extraOrder:
  order: latest
  proxy:
    host: '代理host'
    port: '代理端口'
  extra_options:
    key: value
```

### 报错信息（建议使用截图，请尽量截取全部把错误信息）

```
$ hexo bangumi -u
INFO  Validating config
INFO  Getting bangumis, please wait...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type string ('代理端口').
    at new NodeError (node:internal/errors:399:5)
    at validatePort (node:internal/validators:390:11)
    at lookupAndConnect (node:net:1227:5)
    at Socket.connect (node:net:1193:5)
    at Agent.connect [as createConnection] (node:net:243:17)
    at Agent.createSocket (node:_http_agent:341:26)
    at Agent.addRequest (node:_http_agent:288:10)
    at new ClientRequest (node:_http_client:343:16)
    at TunnelingAgent.request (node:http:98:10)
    at TunnelingAgent.createSocket (F:\HexoBlog\node_modules\tunnel\lib\tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (F:\HexoBlog\node_modules\tunnel\lib\tunnel.js:207:41)
    at TunnelingAgent.addRequest (F:\HexoBlog\node_modules\tunnel\lib\tunnel.js:84:8)
    at new ClientRequest (node:_http_client:343:16)
    at Object.request (node:https:360:10)
    at RedirectableRequest._performRequest (F:\HexoBlog\node_modules\follow-redirects\index.js:326:24)
    at new RedirectableRequest (F:\HexoBlog\node_modules\follow-redirects\index.js:100:8)
    at Object.request (F:\HexoBlog\node_modules\follow-redirects\index.js:532:14)
    at dispatchHttpRequest (F:\HexoBlog\node_modules\hexo-bilibili-bangumi\node_modules\axios\dist\node\axios.cjs:2932:21)
    at F:\HexoBlog\node_modules\hexo-bilibili-bangumi\node_modules\axios\dist\node\axios.cjs:2622:5
    at new Promise (<anonymous>)
    at wrapAsync (F:\HexoBlog\node_modules\hexo-bilibili-bangumi\node_modules\axios\dist\node\axios.cjs:2602:10)
    at http (F:\HexoBlog\node_modules\hexo-bilibili-bangumi\node_modules\axios\dist\node\axios.cjs:2640:10)
    at Axios.request (F:\HexoBlog\node_modules\hexo-bilibili-bangumi\node_modules\axios\dist\node\axios.cjs:3877:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_SOCKET_BAD_PORT'
}

Node.js v18.14.0
```

### 插件版本

1.8.9(最新)

### 环境信息（使用`hexo -v`命令查看）

```shell
$ hexo -v
INFO  Validating config
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 18.14.0
v8: 10.2.154.23-node.22
uv: 1.44.2
zlib: 1.2.13
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.51.0
napi: 8
llhttp: 6.0.10
uvwasi: 0.0.14
acorn: 8.8.1
simdutf: 3.1.0
undici: 5.14.0
openssl: 3.0.7+quic
cldr: 42.0
icu: 72.1
tz: 2022g
unicode: 15.0
ngtcp2: 0.8.1
nghttp3: 0.7.0
```
```
